contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #seqinspector channel"
    url: https://nfcore.slack.com/channels/seqinspector
    about: Discussion about the nf-core/seqinspector pipeline
